name: frame_camera_parameter_sweep
description: "Frame app for sweeping over a variety of exposure and gain parameters"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.3.0
  logging: ^1.2.0
  share_plus: ^10.1.0
  simple_frame_app: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - packages/simple_frame_app/lua/battery.min.lua
    - packages/simple_frame_app/lua/camera.min.lua
    - packages/simple_frame_app/lua/data.min.lua
    - assets/frame_app.min.lua